# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from navigator._transport.navigator.consumer.v1 import consumer_pb2 as navigator_dot_consumer_dot_v1_dot_consumer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in navigator/consumer/v1/consumer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NavigatorConsumerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Negotiate = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/Negotiate',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.NegotiateRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.NegotiateResponse.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/OpenSession',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OpenSessionResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/Snapshot',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/CloseSession',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/navigator.consumer.v1.NavigatorConsumer/SubscribeEvents',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SubscribeEventsResponse.FromString,
                _registered_method=True)
        self.ReadEvents = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ReadEvents',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadEventsRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadEventsResponse.FromString,
                _registered_method=True)
        self.StartOperation = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/StartOperation',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.StartOperationRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.StartOperationResponse.FromString,
                _registered_method=True)
        self.OperationSnapshot = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/OperationSnapshot',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OperationSnapshotRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OperationSnapshotResponse.FromString,
                _registered_method=True)
        self.ParticipantSnapshot = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ParticipantSnapshot',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ParticipantSnapshotRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ParticipantSnapshotResponse.FromString,
                _registered_method=True)
        self.MessageSnapshot = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/MessageSnapshot',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.MessageSnapshotRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.MessageSnapshotResponse.FromString,
                _registered_method=True)
        self.CancelSubtree = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/CancelSubtree',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CancelSubtreeRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CancelSubtreeResponse.FromString,
                _registered_method=True)
        self.ResumeSession = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ResumeSession',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResumeSessionRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResumeSessionResponse.FromString,
                _registered_method=True)
        self.ResolveUncertainty = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ResolveUncertainty',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResolveUncertaintyRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResolveUncertaintyResponse.FromString,
                _registered_method=True)
        self.RegisterTool = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/RegisterTool',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RegisterToolRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RegisterToolResponse.FromString,
                _registered_method=True)
        self.ProvideTools = channel.stream_stream(
                '/navigator.consumer.v1.NavigatorConsumer/ProvideTools',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ToolProviderRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ToolProviderResponse.FromString,
                _registered_method=True)
        self.WriteArtifact = channel.stream_unary(
                '/navigator.consumer.v1.NavigatorConsumer/WriteArtifact',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.WriteArtifactRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.WriteArtifactResponse.FromString,
                _registered_method=True)
        self.ReadArtifact = channel.unary_stream(
                '/navigator.consumer.v1.NavigatorConsumer/ReadArtifact',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadArtifactRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadArtifactResponse.FromString,
                _registered_method=True)
        self.ArtifactSnapshot = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ArtifactSnapshot',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ArtifactSnapshotRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ArtifactSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteArtifact = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/DeleteArtifact',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DeleteArtifactRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DeleteArtifactResponse.FromString,
                _registered_method=True)
        self.ApprovalSnapshot = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ApprovalSnapshot',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApprovalSnapshotRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApprovalSnapshotResponse.FromString,
                _registered_method=True)
        self.ApproveApproval = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ApproveApproval',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApproveApprovalRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApproveApprovalResponse.FromString,
                _registered_method=True)
        self.DenyApproval = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/DenyApproval',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DenyApprovalRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DenyApprovalResponse.FromString,
                _registered_method=True)
        self.RevokeApprovalGrant = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/RevokeApprovalGrant',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RevokeApprovalGrantRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RevokeApprovalGrantResponse.FromString,
                _registered_method=True)
        self.ReadProjection = channel.unary_unary(
                '/navigator.consumer.v1.NavigatorConsumer/ReadProjection',
                request_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadProjectionRequest.SerializeToString,
                response_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadProjectionResponse.FromString,
                _registered_method=True)


class NavigatorConsumerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Negotiate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadEvents(self, request, context):
        """Bounded, strictly read-only event polling for inspectors.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OperationSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParticipantSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MessageSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSubtree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveUncertainty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterTool(self, request, context):
        """Requires consumer.tools.v1.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideTools(self, request_iterator, context):
        """A reconnectable, authenticated Consumer provider channel. The first client
        frame is ConnectToolProvider; subsequent frames correlate one invocation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteArtifact(self, request_iterator, context):
        """Requires artifacts.v1. Content never enters ordinary Message payloads.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArtifactSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApprovalSnapshot(self, request, context):
        """Requires approvals.v1. Decisions are accepted only at the authenticated,
        Session-bound trusted Consumer boundary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenyApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeApprovalGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProjection(self, request, context):
        """Requires operational.projections.v1. This RPC is strictly read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NavigatorConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Negotiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Negotiate,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.NegotiateRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.NegotiateResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OpenSessionRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OpenSessionResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SnapshotRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SnapshotResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CloseSessionRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CloseSessionResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.SubscribeEventsResponse.SerializeToString,
            ),
            'ReadEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadEvents,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadEventsRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadEventsResponse.SerializeToString,
            ),
            'StartOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOperation,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.StartOperationRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.StartOperationResponse.SerializeToString,
            ),
            'OperationSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.OperationSnapshot,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OperationSnapshotRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.OperationSnapshotResponse.SerializeToString,
            ),
            'ParticipantSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ParticipantSnapshot,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ParticipantSnapshotRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ParticipantSnapshotResponse.SerializeToString,
            ),
            'MessageSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.MessageSnapshot,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.MessageSnapshotRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.MessageSnapshotResponse.SerializeToString,
            ),
            'CancelSubtree': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSubtree,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CancelSubtreeRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.CancelSubtreeResponse.SerializeToString,
            ),
            'ResumeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSession,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResumeSessionRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResumeSessionResponse.SerializeToString,
            ),
            'ResolveUncertainty': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveUncertainty,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResolveUncertaintyRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResolveUncertaintyResponse.SerializeToString,
            ),
            'RegisterTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTool,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RegisterToolRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RegisterToolResponse.SerializeToString,
            ),
            'ProvideTools': grpc.stream_stream_rpc_method_handler(
                    servicer.ProvideTools,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ToolProviderRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ToolProviderResponse.SerializeToString,
            ),
            'WriteArtifact': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteArtifact,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.WriteArtifactRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.WriteArtifactResponse.SerializeToString,
            ),
            'ReadArtifact': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadArtifact,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadArtifactRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadArtifactResponse.SerializeToString,
            ),
            'ArtifactSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ArtifactSnapshot,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ArtifactSnapshotRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ArtifactSnapshotResponse.SerializeToString,
            ),
            'DeleteArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArtifact,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DeleteArtifactRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DeleteArtifactResponse.SerializeToString,
            ),
            'ApprovalSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ApprovalSnapshot,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApprovalSnapshotRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApprovalSnapshotResponse.SerializeToString,
            ),
            'ApproveApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveApproval,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApproveApprovalRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApproveApprovalResponse.SerializeToString,
            ),
            'DenyApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.DenyApproval,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DenyApprovalRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.DenyApprovalResponse.SerializeToString,
            ),
            'RevokeApprovalGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeApprovalGrant,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RevokeApprovalGrantRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.RevokeApprovalGrantResponse.SerializeToString,
            ),
            'ReadProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProjection,
                    request_deserializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadProjectionRequest.FromString,
                    response_serializer=navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadProjectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'navigator.consumer.v1.NavigatorConsumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('navigator.consumer.v1.NavigatorConsumer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NavigatorConsumer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Negotiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/Negotiate',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.NegotiateRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.NegotiateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/OpenSession',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.OpenSessionRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.OpenSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/Snapshot',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.SnapshotRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/CloseSession',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.CloseSessionRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/SubscribeEvents',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.SubscribeEventsRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.SubscribeEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ReadEvents',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadEventsRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/StartOperation',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.StartOperationRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.StartOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OperationSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/OperationSnapshot',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.OperationSnapshotRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.OperationSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParticipantSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ParticipantSnapshot',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ParticipantSnapshotRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ParticipantSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MessageSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/MessageSnapshot',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.MessageSnapshotRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.MessageSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSubtree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/CancelSubtree',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.CancelSubtreeRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.CancelSubtreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ResumeSession',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResumeSessionRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResumeSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveUncertainty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ResolveUncertainty',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResolveUncertaintyRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ResolveUncertaintyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/RegisterTool',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.RegisterToolRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.RegisterToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideTools(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ProvideTools',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ToolProviderRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ToolProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteArtifact(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/WriteArtifact',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.WriteArtifactRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.WriteArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ReadArtifact',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadArtifactRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArtifactSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ArtifactSnapshot',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ArtifactSnapshotRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ArtifactSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/DeleteArtifact',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.DeleteArtifactRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.DeleteArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApprovalSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ApprovalSnapshot',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApprovalSnapshotRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApprovalSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ApproveApproval',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApproveApprovalRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ApproveApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenyApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/DenyApproval',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.DenyApprovalRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.DenyApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeApprovalGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/RevokeApprovalGrant',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.RevokeApprovalGrantRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.RevokeApprovalGrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/navigator.consumer.v1.NavigatorConsumer/ReadProjection',
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadProjectionRequest.SerializeToString,
            navigator_dot_consumer_dot_v1_dot_consumer__pb2.ReadProjectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
